### ISSUE TITLE
Create a Website design for Coaching classes

### ISSUE THREAD

**Issue by Coder404x2** [ManasiGDeshmukh/HacktoberR#3]
you will have to design a welcome page for this website
About Coaching classes: they are for 11th and 12th JEE & NEET

You may use canva

**Comment by devmusiczz** [comment]
i can work on this issue @ManasiGDeshmukh

**Comment by Somanath2314** [comment]
I am willing to work on it @ManasiGDeshmukh

**Comment by Coder404x2** [comment]
@devmusiczz I have assigned you this issues. Please give update within 2 days. Happy Contributing !!

**Comment by ManasiDeshmukh1** [comment]
hey  pl assign me
